### ISSUE TITLE
ClassCastException from Any to String

### ISSUE THREAD

**Issue by yschimke** [cashapp/certifikit#49]
```
 ./cft --host expired.badssl.com --insecure
java.lang.ClassCastException: class app.cash.certifikit.AnyValue cannot be cast to class java.lang.String (app.cash.certifikit.AnyValue is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at app.cash.certifikit.Certificate.getCommonName(certificates.kt:239)
	at app.cash.certifikit.cli.CertificateOutputKt.prettyPrintCertificate(certificateOutput.kt:47)
	at app.cash.certifikit.cli.Main.prettyPrintChain(Main.kt:188)
	at app.cash.certifikit.cli.Main.queryHost(Main.kt:128)
	at app.cash.certifikit.cli.Main.call(Main.kt:82)
	at app.cash.certifikit.cli.Main.call(Main.kt:46)
```

**Comment by yschimke** [comment]
Difference from a working host

AttributeTypeAndValue(type=2.5.4.3, value=AnyValue(tagClass=0, tag=20, constructed=false, length=12, bytes=[text=*.badssl.com]))

AttributeTypeAndValue(type=2.5.4.3, value=*.google.com)

**Comment by yschimke** [comment]
Presumably tag class 20 instead of 12 or 19.

**Comment by yschimke** [comment]
Fixed but terrible output for unexpected encodings currently.
