### ISSUE TITLE
Failed to re-encode certificate

### ISSUE THREAD

**Issue by yschimke** [cashapp/certifikit#7]
Not a blocker since I have original as X509Certificate

```
java.lang.IllegalArgumentException: failed to decode certificate
	at app.cash.certifikit.Certificate.toX509Certificate(certificates.kt:86)
	at app.cash.certifikit.cli.CertificateOutputKt.certificatePem(certificateOutput.kt:40)
	at app.cash.certifikit.cli.Main.outputCertificate(Main.kt:97)
	at app.cash.certifikit.cli.Main.outputCertificates(Main.kt:90)
	at app.cash.certifikit.cli.Main.queryHost(Main.kt:83)
	at app.cash.certifikit.cli.Main.run(Main.kt:67)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at app.cash.certifikit.cli.Main$Companion.main(Main.kt:183)
	at app.cash.certifikit.cli.Main.main(Main.kt)
Caused by: java.security.cert.CertificateParsingException: java.io.IOException: Invalid encoding of BasicConstraints
	at java.base/sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:171)
	at java.base/sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1840)
	at java.base/sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:192)
	at java.base/sun.security.provider.X509Factory.parseX509orPKCS7Cert(X509Factory.java:476)
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificates(X509Factory.java:361)
	at java.base/java.security.cert.CertificateFactory.generateCertificates(CertificateFactory.java:478)
	at app.cash.certifikit.Certificate.toX509Certificate(certificates.kt:79)
	... 14 more
Caused by: java.io.IOException: Invalid encoding of BasicConstraints
	at java.base/sun.security.x509.BasicConstraintsExtension.<init>(BasicConstraintsExtension.java:131)
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor1.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at java.base/sun.security.x509.CertificateExtensions.parseExtension(CertificateExtensions.java:113)
	at java.base/sun.security.x509.CertificateExtensions.init(CertificateExtensions.java:88)
	at java.base/sun.security.x509.CertificateExtensions.<init>(CertificateExtensions.java:78)
	at java.base/sun.security.x509.X509CertInfo.parse(X509CertInfo.java:709)
	at java.base/sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:169)
	... 20 more
```

**Comment by yschimke** [comment]
I think I lost the context - I can try to reproduce in a test when/if it's not obvious, but it's not clear this is something you generally want to support at the moment.

**Comment by yschimke** [comment]
Will close for now as unreproducible but I suspect it's still there
